apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: test 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test	
	template:
	  metadata:
	    labels:
		  app: test
	  spec:
	    containers:
		- command:
		  - /home/testuser/entrypoint.sh
		  image: 
		  imagePullPolicy: IfNotPresent
		  name: bharat-lts
		  ports:
		  - containerPort: 8080
		    protocol: TCP
		  resources:
		    limits:
			  cpu: "1000Mi"
			  memory: "1Gi"
			requests:
			  cpu: "1000Mi"
			  memory: "1Gi"
			  
