apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: test
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: data
    emptyDir: {}
  containers:
  - command:
    - /home/testuser/entrypoint.sh
    image:
    imagePullPolicy: IfNotPresent
    name: bharat-tls
    volumeMounts:
    - name: data
      mountPath: /usr/local/data
    resources:
      limits:
        cpu: "1Mi"
        memory: "1Gi"
      requests:
        cpu: "1Mi"
        memory: "1Gi"
        
