apiVersion: apps/v1
kind:  StatefulSet
metadata:
  name: sample-statefulset
  labels:
    app: test
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  selector:
    matchLabels: 
      app: test
  serviceName: sample-service
  template:
    metadata:
      labels:
        app: test
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      cotainers:
      - command:
        - /home/testuser/entrypoint.sh
        image:
        imagePullPolicy: IfNotPresent
        name: bharat-tls
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 1433
          protocol: TCP
        resources:  
          limits: 
            cpu: "1000Mi"
            memory: "1Gi"
          requests:
            cpu: "1000Mi"
            memory: "1Gi"
        volumeMounts:
        - mountPath: /usr/local/data
          name: data
  volumeClaimTemplates:
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "10Gi"
      storageClassName: "sc-test"
            
        
        
